TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += ttiplp.db
DATA += ttiplp.proto

#=======================================
include $(TOP)/configure/RULES
